name: Build on Merge

on:
  push: 
    branches:
      - main
    paths-ignore:
      - 'docker/**'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Run rebuild script
        run: /root/patchmon/platform/scripts/app_build.sh ${{ github.ref_name }}
